[Artur Kostiuk]some of task
griddynamics/ui-intshp2-cp-okapi pull request #20
Opened 2019-01-28 16:19 UTC by art1kos

2019-01-28 16:20 UTC, art1kos commented
https://issues.griddynamics.net/browse/UIT-25

2019-01-28 17:07 UTC, dverbovyi requested changes
@art1kos looks good.

please fix minor comments

and add add-to-cart button handler with the ability to send the request to add-to-cart/ route with selected product options

POST add-to-cart/<product-id>

2019-01-28 17:07 UTC, dverbovyi commented on src/app/product-details-page/components/product-description/product-order/product-order.component.ts
> +  changePlus() {
how the plus can be changed?) The name doesn't describe what this function do

2019-01-28 17:07 UTC, dverbovyi commented on src/app/product-details-page/components/product-description/product-order/product-order.component.ts
> +  changeMinus() {
The name doesn't describe what this function do

2019-01-29 09:15 UTC, art1kos commented on src/app/product-details-page/components/product-description/product-order/product-order.component.ts
> +    this.productConfiguration.price = this.price;
what this comment mean?

2019-01-29 17:04 UTC, dverbovyi commented on src/app/product-details-page/components/product-description/product-order/product-order.component.ts
> +    this.productConfiguration.price = this.price;
the default property value

2019-01-29 17:37 UTC, dverbovyi approved these changes
@art1kos good, I'm merging it, please provide missed tests for product count and size selection

2019-01-29 17:37 UTC, dverbovyi commented on src/app/product-details-page/components/product-description/product-order/product-order.component.spec.ts
> +  it('should create', () => {
add product-order cases (size, amount selection)

2019-01-29 17:38 UTC, merged