[Pavlo Turchyn]UIT-44 related products initial commit
griddynamics/ui-intshp2-cp-okapi pull request #21
Opened 2019-01-28 16:25 UTC by FabianMoretti

2019-01-28 16:47 UTC, dverbovyi requested changes

2019-01-28 16:47 UTC, dverbovyi commented on src/app/product-details-page/components/product-details-page/product-details-page.component.spec.ts
> +  xit('should create', () => {
why did you skip it?

2019-01-28 16:47 UTC, dverbovyi commented on src/app/product-details-page/product-details-page.module.ts
>      CommonModule,
remove CommonModule. It's already in the shared

2019-01-28 16:47 UTC, dverbovyi commented on src/app/shared/components/related-products/related-products.component.spec.ts
> +  xit('should create', () => {
why did you skip it?

2019-01-28 16:47 UTC, dverbovyi commented on src/app/shared/shared.module.ts
> +import { RelatedProductsComponent } from './components/related-products/related-products.component';
This is not shared component. It's only related to PDP

2019-01-28 16:47 UTC, dverbovyi commented on src/app/shared/shared.module.ts
> +    RelatedProductsComponent
This is not shared component. It's only related to PDP

2019-01-28 16:47 UTC, dverbovyi commented on src/app/shared/shared.module.ts
> +    RelatedProductsComponent
RelatedProductsComponent is not shared component. It's only related to PDP

2019-01-29 06:52 UTC, dverbovyi commented
I provided a technical vision in story comment

https://issues.griddynamics.net/browse/UIT-44

2019-01-29 14:11 UTC, FabianMoretti commented
https://issues.griddynamics.net/browse/UIT-44

2019-01-29 14:23 UTC, dverbovyi requested changes
@FabianMoretti 

related-products.component.scss

2019-01-29 14:23 UTC, dverbovyi commented on src/app/home-page/components/home-page/home-page.component.ts
> +    relatedProducts: [],
we don't need related products for Home-Page

2019-01-29 14:23 UTC, dverbovyi commented on src/app/product-details-page/components/product-details-page/related-products/related-products.component.ts
> +  json = require('../../../../mocks/pdp.json');
it should be HTTP request

2019-01-29 14:23 UTC, dverbovyi commented on src/app/mocks/pdp.json
> +[{
it shouldn't be an array. Only 1 product with related inside

2019-01-29 14:23 UTC, dverbovyi commented on src/app/product-details-page/components/product-details-page/related-products/related-products.component.html
> +<div *ngIf="this.relatedProductsArr.length > 0">
> 0 can be omitted,  

just.length

2019-01-29 14:23 UTC, dverbovyi commented on src/app/shared/interfaces/product.ts
> +  relatedProducts: Array<IProduct>;
this is optional 

relatedProducts?: Array<IProduct>

2019-01-30 11:24 UTC, dverbovyi requested changes

2019-01-30 11:24 UTC, dverbovyi commented on src/app/home-page/components/home-page/home-page.component.ts
> +    relatedProducts: [],
delete related from home-page

2019-01-30 11:24 UTC, dverbovyi commented on src/app/core/services/product-details-page.service.ts
> +  getRelatedProducts() {
getProduct(id:String)

2019-01-30 11:24 UTC, dverbovyi commented on src/app/core/services/product-details-page.service.ts
> +  constructor(private mocks: DataService) {}
private dataService: DataService

2019-01-30 11:24 UTC, dverbovyi commented on src/app/product-details-page/components/product-details-page/product-details-page.component.html
> +<app-related-products></app-related-products>
related products should be passed as an attribute from product-details component
<app-related-products [products]="relatedProducts" ></app-related-products>

2019-01-30 11:24 UTC, dverbovyi commented on src/app/product-details-page/components/product-details-page/related-products/related-products.component.html
> +<div *ngIf="relatedProductsArrLength">
relatedProducts.length

2019-01-30 11:24 UTC, dverbovyi commented on src/app/product-details-page/components/product-details-page/related-products/related-products.component.ts
> +  products: IProduct;
Input() products: IProduct[] = [];

2019-01-30 11:24 UTC, dverbovyi commented on src/app/product-details-page/components/product-details-page/related-products/related-products.component.ts
> +  id: number;
delete the all stuff below

2019-01-30 11:24 UTC, dverbovyi commented on src/app/product-details-page/components/product-details-page/related-products/related-products.component.ts
> +    this.mock.getRelatedProducts().subscribe(data => {
the request should happened in the page-level component.

you should 

```
this.dataService.getProduct(routeId)
```

2019-01-30 11:24 UTC, dverbovyi commented on src/app/shared/pipes/safe.pipe.spec.ts
> +import { AdvertisingAreaComponent } from '../components/advertising-area/advertising-area.component';
This test related to Pipe. no components should be here

2019-01-30 14:56 UTC, dverbovyi requested changes

2019-01-30 14:56 UTC, dverbovyi commented on src/app/core/services/product-details-page.service.spec.ts
> +  it('should be created', () => {
add an additional test for the service which validates getProduct

2019-01-30 14:56 UTC, dverbovyi commented on src/app/product-details-page/components/product-details-page/related-products/related-products.component.ts
> +  @Input() products: IProduct[];
@Input() products: IProduct[] = []; //define with a default value

2019-01-30 14:56 UTC, dverbovyi commented on src/app/product-details-page/components/product-details-page/related-products/related-products.component.ts
> +  ngOnChanges(): void {
you don't need this

2019-01-30 14:56 UTC, dverbovyi commented on src/app/product-details-page/components/product-details-page/product-details-page.component.ts
> +    this.dataService.getProduct(this.routeId).subscribe(data => this.relatedProducts = data.relatedProducts);
on this line the routeId is undefined

use the next

```ts
ngOnInit() {
   this.productSubscription = this.route.params.pipe(
      mergeMap(({id)) => this.dataService.getProduct(id)
   ).subscribe(product => this.product = product);
}

ngOnDestroy() {
   this.productSubscription.unsubscribe();
}
```

2019-01-30 14:56 UTC, dverbovyi commented on src/app/product-details-page/components/product-details-page/product-details-page.component.ts
> +  routeId: String;
remove

2019-01-30 14:56 UTC, dverbovyi commented on src/app/product-details-page/components/product-details-page/product-details-page.component.ts
>    productInfo = {
remove

it should be taken from product response

2019-01-30 14:56 UTC, dverbovyi commented on src/app/product-details-page/components/product-details-page/product-details-page.component.ts
> +  relatedProducts: IProduct[] = [];
remove

2019-01-30 14:56 UTC, dverbovyi commented on src/app/product-details-page/components/product-details-page/product-details-page.component.html
> +<app-related-products [products]="relatedProducts" >
<app-related-products [products]="product.relatedProducts" >

2019-01-30 14:56 UTC, dverbovyi commented on src/app/core/services/product-details-page.service.ts
> +  getProduct(id: String) {
specify the return type
```ts
getProduct(id: String): Observable<IProduct> {
...
}
```

2019-01-31 13:56 UTC, dverbovyi requested changes

2019-01-31 13:56 UTC, dverbovyi commented on src/app/product-details-page/components/product-details-page/product-details-page.component.ts
> +  productSubscription;
private

2019-01-31 13:56 UTC, dverbovyi commented on src/app/product-details-page/components/product-details-page/product-details-page.component.html
> +<app-related-products [products]="product?.relatedProducts"></app-related-products>
it's better not to instantiate related-product component at all if there are no products
```html
<app-related-products *ngIf="product?.relatedProducts" [products]="product.relatedProducts"></app-related-products>
```

2019-01-31 13:56 UTC, dverbovyi commented on src/app/core/services/product-details-page.service.spec.ts
> +import { HttpClientModule } from '@angular/common/http';
### Breaking the Styleguide detected

Separete "**Theirs** first from **Ours**". Aplly this pattern for all files

#### Example how should be
https://angular.io/guide/styleguide#import-line-spacing

![screen shot 2019-01-31 at 15 15 17](https://user-images.githubusercontent.com/9499109/52056575-4ae8a600-256b-11e9-8ece-e091e835e988.png)

2019-01-31 13:56 UTC, dverbovyi commented on src/app/product-details-page/components/product-details-page/related-products/related-products.component.html
> +<div *ngIf="products?.length">
Move this check to the parent component and just don't render the child one. Child component should definitely have the product and doesn't validate it's absence

2019-01-31 13:56 UTC, dverbovyi commented on src/app/product-details-page/components/product-details-page/related-products/related-products.component.ts
> +  ngOnChanges(): void {
not resolved

2019-01-31 13:56 UTC, dverbovyi commented on src/app/shared/components/advertising-area/advertising-area.component.spec.ts
>  import { By } from '@angular/platform-browser';
broken styleguide

own imports shoud come after core and third-parties

2019-02-01 13:44 UTC, dverbovyi approved these changes

2019-02-01 13:45 UTC, merged