[Natalia Falinska] UIT 34 recently viewed
griddynamics/ui-intshp2-cp-okapi pull request #23
Opened 2019-01-28 16:30 UTC by NFalinska

2019-01-30 14:59 UTC, NFalinska commented
https://issues.griddynamics.net/secure/RapidBoard.jspa?rapidView=298&view=detail&selectedIssue=UIT-34

2019-01-30 16:51 UTC, dverbovyi requested changes

2019-01-30 16:51 UTC, dverbovyi commented on src/app/app.component.ts
> +// import { RecentlyViewedService } from './shared/components/recently-viewed/recently-viewed.service';
wtf?

2019-01-30 16:51 UTC, dverbovyi commented on src/app/app.component.ts
> +    // recentlyViewedService.loadRouting();
wtf?

2019-01-30 16:51 UTC, dverbovyi commented on src/app/product-details-page/components/product-details-page/product-details-page.component.html
> +<!-- <p>{{stored.id}}</p> -->
?

2019-01-30 16:51 UTC, dverbovyi commented on src/app/home-page/components/home-page/home-page.component.html
> +<app-carousel [productsLength]="products.length">
revert this change

2019-01-30 16:51 UTC, dverbovyi commented on src/app/home-page/components/home-page/home-page.component.html
> +<app-carousel *ngIf="viewedItems" [productsLength]="viewedItems.length">
create recently viewed component

2019-01-30 16:51 UTC, dverbovyi commented on src/app/home-page/components/home-page/home-page.component.ts
> +  viewedItems = JSON.parse(localStorage.getItem('recentlyViewed'));
move to recently viewed component

2019-01-30 16:51 UTC, dverbovyi commented on src/app/product-details-page/components/product-details-page/product-details-page.component.ts
> +    stored.unshift(newProd);
only id has to be stored

2019-02-01 14:59 UTC, dverbovyi requested changes

2019-02-01 14:59 UTC, dverbovyi commented on src/app/home-page/components/home-page/home-page.component.html
> +<app-carousel [productsLength]="products.length">
ping

2019-02-01 14:59 UTC, dverbovyi commented on src/app/product-details-page/components/product-details-page/product-details-page.component.ts
> +      let isInArray = 0;
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes

2019-02-01 14:59 UTC, dverbovyi commented on src/app/shared/components/carousel/carousel.component.scss
> +  // justify-content: space-between;
ping

2019-02-01 14:59 UTC, dverbovyi commented on src/app/shared/components/carousel/carousel.component.ts
> +  @Input() productsLength;
revert all changes in carousel

2019-02-01 14:59 UTC, dverbovyi commented on src/app/shared/components/recently-viewed/recently-viewed.component.ts
> +  viewedItems: IProduct [] = [{
pass products as Input property

2019-02-01 14:59 UTC, dverbovyi commented on src/app/shared/components/recently-viewed/recently-viewed.component.html
> +<app-carousel *ngIf="viewedItems.length" [productsLength]="viewedItems.length">
where is app-heading component with an appropriate title?

2019-02-01 14:59 UTC, dverbovyi commented on src/app/home-page/components/home-page/home-page.component.html
> +<app-recently-viewed></app-recently-viewed>
<app-recently-viewed *ngIf="products.length" [products]="products"></app-recently-viewed>

2019-02-04 10:22 UTC, dverbovyi requested changes
@NFalinska good job, please fix minor comments

2019-02-04 10:22 UTC, dverbovyi commented on src/app/product-details-page/components/product-details-page/product-details-page.component.ts
> +  productInfo = {
remove this mocked object. it's not using anymore

2019-02-04 10:22 UTC, dverbovyi commented on src/app/product-details-page/components/product-details-page/product-details-page.component.ts
> +    const stored = JSON.parse(localStorage.getItem('recentlyViewed')) || [];
rename to 

`const recentlyViewedIds = JSON.parse(localStorage.getItem('recentlyViewedIds'))`

2019-02-04 10:22 UTC, dverbovyi commented on src/app/shared/components/recently-viewed/recently-viewed.component.html
> +<app-heading *ngIf="products.length" [alertText]="'recently viewed'" [headingText]="'list'"></app-heading>
recently viewed component should not render at all if products are absent. So please remove this check as you have it in the parent component

2019-02-04 10:22 UTC, dverbovyi commented on src/app/shared/components/recently-viewed/recently-viewed.component.html
> +<app-carousel *ngIf="products.length">
the same as above

2019-02-04 10:22 UTC, dverbovyi commented on src/app/product-details-page/components/product-details-page/product-details-page.component.ts
> +    const newProdId = this.route.snapshot.params['id'];
move all this logic related to recently viewed into a separate function called markAsRecentlyViewed

2019-02-04 10:22 UTC, dverbovyi commented on src/app/shared/components/recently-viewed/recently-viewed.component.ts
> +      this.products = [];
else isn't needed here

2019-02-04 17:42 UTC, dverbovyi approved these changes

2019-02-04 17:42 UTC, merged