[Pavlo Turchyn] working version with possibility to switch type of animation & covere…
griddynamics/ui-intshp2-cp-okapi pull request #33
Opened 2019-02-08 13:11 UTC by FabianMoretti

…d with unit tests

2019-02-08 13:13 UTC, FabianMoretti commented
https://issues.griddynamics.net/browse/UIT-43

2019-02-08 15:52 UTC, dverbovyi requested changes
@FabianMoretti please apply the Strategy design pattern for this task to get rid of the code duplication and leave the opportunity to add several more slide-animation types

https://refactoring.guru/uk/design-patterns/strategy

2019-02-08 15:52 UTC, dverbovyi commented on src/app/home-page/components/slideshow/slideshow.component.spec.ts
>      expect(functionsReturn).toBeUndefined();
this expect validate nothing

2019-02-11 13:37 UTC, dverbovyi commented
@FabianMoretti get rid of code duplication

2019-02-12 14:16 UTC, dverbovyi requested changes
@FabianMoretti please fix test with toBeUndefined. They validate nothing

2019-02-12 14:16 UTC, dverbovyi commented on src/app/home-page/components/slideshow/slideshow.component.spec.ts
> +    expect(component.intervalStart).toBe(76);
it can be in varied environments. Just check typeof number

2019-02-12 14:16 UTC, dverbovyi commented on src/app/home-page/components/slideshow/slideshow.component.spec.ts
> +    expect(component.continue()).toBeUndefined();
all these methods (pause/continue) return undefined
check the properties they change, refactor the rest one with toBeUndefined checks

see example:
```
component.isStoped = true;
component.pause();
expect(this.isHovered).toBe(false) 
```

2019-02-12 14:53 UTC, dverbovyi approved these changes

2019-02-12 14:54 UTC, merged