[Natalia Falinska] lazy load
griddynamics/ui-intshp2-cp-okapi pull request #34
Opened 2019-02-08 15:44 UTC by NFalinska

2019-02-11 15:26 UTC, NFalinska commented
https://issues.griddynamics.net/secure/RapidBoard.jspa?rapidView=298&view=detail&selectedIssue=UIT-40

2019-02-13 13:27 UTC, Roman-Klimkevych commented on src/app/product-list-page/components/product-list-page/product-list-page.component.html
> +  </div>
why do you need this change?

2019-02-13 13:43 UTC, Roman-Klimkevych approved these changes

2019-02-13 21:10 UTC, Roman-Klimkevych commented on src/app/home-page/components/slideshow/slideshow.component.ts
> +
Do you need this extra blanc line here?

2019-02-13 21:10 UTC, Roman-Klimkevych commented on src/app/home-page/components/slideshow/slideshow.component.html
> +          </app-lazy-load>
Indentation is a little bit off here.

2019-02-13 21:10 UTC, Roman-Klimkevych commented on src/app/home-page/components/slideshow/slideshow.component.spec.ts
>        imports: [HttpClientTestingModule]
You have to be consistent with the spaces in brackets.

2019-02-13 21:10 UTC, Roman-Klimkevych commented on src/app/product-details-page/components/product-description/product-description.component.spec.ts
You import this component here but don't use it.

2019-02-13 21:10 UTC, Roman-Klimkevych commented on src/app/product-details-page/components/product-description/product-image-preview/product-image-preview.component.spec.ts
> +import { LazyLoadComponent } from 'src/app/shared/components/lazy-load/lazy-load.component';
You import this component here but don't use it.

2019-02-13 21:10 UTC, Roman-Klimkevych commented on src/app/shared/components/lazy-load/lazy-load.component.ts
> +      target.classList.add('loadeding');
a spelling error `'loadeding'`

2019-02-13 21:10 UTC, Roman-Klimkevych commented on src/app/product-details-page/components/product-description/product-image-preview/product-image-preview.component.spec.ts
> +      declarations: [ProductImagePreviewComponent, ProductDescriptionComponent, ProductOrderComponent, ZoomComponent ],
When you have an array spreading over several lines, I think it's better to have each item on a separate line, like this:
```
declarations: [
  ProductImagePreviewComponent,
  ProductDescriptionComponent,
  ProductOrderComponent,
  ZoomComponent
],
```

2019-02-14 11:41 UTC, dverbovyi requested changes

2019-02-14 11:41 UTC, dverbovyi commented on src/app/shared/components/lazy-load/lazy-load.component.ts
> +  observer: IntersectionObserver;
this should be private

2019-02-14 11:41 UTC, dverbovyi commented on src/app/shared/components/lazy-load/lazy-load.component.ts
> +  options: any = {
make private

2019-02-14 11:41 UTC, dverbovyi commented on src/app/shared/components/lazy-load/lazy-load.component.ts
> +    const images = this.element.nativeElement.querySelectorAll('.lazy-load');
`if(!images) return`

2019-02-14 11:41 UTC, dverbovyi commented on src/app/shared/components/lazy-load/lazy-load.component.ts
> +  fetchImage = (url) => {
1) make private
2) specify parameter type
3) it should be declared as class method not property: 
`private fetchImage(url: String):void { ... }`

2019-02-14 11:41 UTC, dverbovyi commented on src/app/shared/components/lazy-load/lazy-load.component.ts
> +  loadImage = (target) => {
this should be class method not arrow function
```ts
private loadImage(target: HTMLElement): void {...}
```

2019-02-14 11:41 UTC, dverbovyi commented on src/app/shared/components/lazy-load/lazy-load.component.ts
> +  handleIntersection = (entries, observer) => {
same here

2019-02-14 11:41 UTC, dverbovyi commented on src/app/shared/components/product-item/product-item-short/product-item-short.component.scss
> +.loading {
you don't need this class

add default style directly for .lazy-load

2019-02-14 11:41 UTC, dverbovyi commented on src/app/shared/components/product-item/product-item.component.ts
> +  public _currentSwatch;
it should be private

2019-02-14 11:41 UTC, dverbovyi commented on src/app/shared/components/carousel/carousel-item/carousel-item.component.spec.ts
> +import { LazyLoadComponent } from '../../lazy-load/lazy-load.component';
this component has not being used in this file

2019-02-14 11:41 UTC, dverbovyi commented on src/app/shared/components/carousel/carousel.component.spec.ts
> +import { LazyLoadComponent } from '../lazy-load/lazy-load.component';
this component has not being used in this file

2019-02-14 11:41 UTC, dverbovyi commented on src/app/shared/components/lazy-load/lazy-load.component.spec.ts
> +  it('should create', () => {
need more tests

2019-02-14 11:41 UTC, dverbovyi commented on src/app/shared/components/load-more/load-more.component.spec.ts
> +import { ProductItemComponent } from '../product-item/product-item.component';
this component has not being used in this file

2019-02-14 11:41 UTC, dverbovyi commented on src/app/shared/components/product-item/product-item.component.scss
> +.loaded {
duplicated styles. Move to lazy-load.component.scss

2019-02-14 11:41 UTC, dverbovyi commented on src/app/shared/components/product-item/product-item.component.spec.ts
> +  it('should return right color', () => {
weird test. nothing in expect

2019-02-15 09:56 UTC, dverbovyi approved these changes

2019-02-15 09:56 UTC, dverbovyi commented on src/app/shared/components/carousel/carousel.component.scss
> +  margin: 0 $content-padding;
please revert this line

2019-02-15 09:56 UTC, dverbovyi commented on src/app/shared/components/carousel/carousel.component.scss
> +  margin: 0 $content-padding;
@NFalinska

2019-02-15 10:50 UTC, merged