[Pavlo Turchyn]_uit-39_API integration
griddynamics/ui-intshp2-cp-okapi pull request #45
Opened 2019-02-18 13:24 UTC by FabianMoretti

2019-02-18 14:36 UTC, dverbovyi requested changes

2019-02-18 14:36 UTC, dverbovyi commented on src/app/home-page/components/home-page/home-page.component.ts
> +      this.dataService.get('api/homepage').subscribe(data => {
3 requests api/homepage. You need only 1

2019-02-18 14:36 UTC, dverbovyi commented on src/app/home-page/components/home-page/home-page.component.ts
> +      this.dataService.get('api/homepage').subscribe(data => {
also unsubscription is needed on component destroy

2019-02-19 09:02 UTC, Roman-Klimkevych commented on src/app/home-page/components/home-page/home-page.component.ts
> +import { environment } from 'src/environments/environment';
`environment` is imported but never used

2019-02-19 09:02 UTC, Roman-Klimkevych commented on src/app/home-page/components/home-page/home-page.component.ts
> +      this.dataService.get('api/homepage').subscribe(data => {
`'api/homepage' ` should not be hardcoded.

2019-02-20 17:31 UTC, dverbovyi commented
a new one https://github.com/griddynamics/ui-intshp2-cp-okapi/pull/48

2019-02-20 17:31 UTC, closed without merging