[Artur Kostiuk]uit 64 swatch selection
griddynamics/ui-intshp2-cp-okapi pull request #50
Opened 2019-02-22 15:21 UTC by art1kos

2019-02-23 09:03 UTC, dverbovyi requested changes
@art1kos good, please fix minor comments

2019-02-23 09:03 UTC, dverbovyi commented on src/app/product-details-page/components/product-description/product-description.component.html
> +          <app-product-order (selectedSwatchImg)="imgChanger($event)" [product]="product"></app-product-order>
imgChanger?))))) xD please rename

2019-02-23 09:03 UTC, dverbovyi commented on src/app/product-details-page/components/product-description/product-description.component.ts
> +  imgChanger(e) {
onSwatchSelect

2019-02-23 09:03 UTC, dverbovyi commented on src/app/product-details-page/components/product-description/product-description.component.html
> +          <app-product-order (selectedSwatchImg)="imgChanger($event)" [product]="product"></app-product-order>
(swatchSelect)="onSwatchSelect"

2019-02-23 09:03 UTC, dverbovyi commented on src/app/product-details-page/components/product-description/product-image-preview/product-image-preview.component.ts
> +  @Input() selectedColorFromOrder;
selectedSwatch

2019-02-25 09:37 UTC, art1kos commented
https://issues.griddynamics.net/browse/UIT-64

2019-02-25 13:48 UTC, dverbovyi approved these changes

2019-02-25 13:48 UTC, merged